export default [
'Checksum',
'UNIX Time Stamp',
'Mission ID',
'Platform Tail Number',
'Platform Heading Angle',
'Platform Pitch Angle',
'Platform Roll Angle',
'Platform True Airspeed',
'Platform Indicated Airspeed',
'Platform Designation',
'Image Source Sensor',
'Image Coordinate System',
'Sensor Latitude',
'Sensor Longitude',
'Sensor True Altitude',
'Sensor Horizontal Field of View',
'Sensor Vertical Field of View',
'Sensor Relative Azimuth Angle',
'Sensor Relative Elevation Angle',
'Sensor Relative Roll Angle',
'Slant Range',
'Target Width',
'Frame Center Latitude',
'Frame Center Longitude',
'Frame Center Elevation',
'Offset Corner Latitude Point 1',
'Offset Corner Longitude Point 1',
'Offset Corner Latitude Point 2',
'Offset Corner Longitude Point 2',
'Offset Corner Latitude Point 3',
'Offset Corner Longitude Point 3',
'Offset Corner Latitude Point 4',
'Offset Corner Longitude Point 4',
'Icing Detected',
'Wind Direction',
'Wind Speed',
'Static Pressure',
'Density Altitude',
'Outside Air Temperature',
'Target Location Latitude',
'Target Location Longitude',
'Target Location Elevation',
'Target Track Gate Width',
'Target Track Gate Height',
'Target Error Estimate - CE90',
'Target Error Estimate - LE90',
'Generic Flag Data 01',
'Security Local Metadata Set',
'Differential Pressure',
'Platform Angle of Attack',
'Platform Vertical Speed',
'Platform Sideslip Angle',
'Airfield Barometric Pressure',
'Airfield Elevation',
'Relative Humidity',
'Platform Ground Speed',
'Ground Range',
'Platform Fuel Remaining',
'Platform Call Sign',
'Weapon Load',
'Weapon Fired',
'Laser PRF Code',
'Sensor Field of View Name',
'Platform Magnetic Heading',
'UAS LDS Version Number',
'Target Location Covariance Matrix',
'Alternate Platform Latitude',
'Alternate Platform Longitude',
'Alternate Platform Altitude',
'Alternate Platform Name',
'Alternate Platform Heading',
'Event Start Time - UTC',
'RVT Local Data Set'
]
